### ISSUE TITLE
Nice job 👌

### ISSUE THREAD

**Issue by frosas** [byohannes/job-listings-react#1]
This is not really an issue, I just wanted to say how well done this project is 😊

Some parts of the code are really neat, I like this one:

https://github.com/byohannes/job-listings-react/blob/8e40b6e40d36cf023511ef5886d586a9aa4375dd/src/components/MainJobsBoard.js#L37-L42

(BTW, you can use `includes()` instead of `indexOf()`)

**Comment by byohannes** [comment]
@frosas  thanks for your positive and motivating message and all of this is the hard efforts you are putting on us to be well-equpped developers. Thanks!
