### ISSUE TITLE
Filter bar is not hidden when no categories are selected

### ISSUE THREAD

**Issue by frosas** [byohannes/job-listings-react#2]
It's a small detail but that's what the design specifies ;)

<img width="1063" alt="Screenshot_2020-06-06_at_20_39_44" src="https://user-images.githubusercontent.com/50098/83953169-fb3c7d80-a835-11ea-856b-a197f2f50050.png">

**Comment by byohannes** [comment]
@frosas I have resoled it now by using a conditionality of the length of the filter bar such as
 {filters.length>0 &&
        <FilterBar
          filters={filters}
          clearFilters={clearFilters}
          removeFilter={removeTagFromFilter}
        />}
thanks, again for spotting it out.

**Comment by frosas** [comment]
Looks good 👍
