### ISSUE TITLE
Some elements don't appear clickable

### ISSUE THREAD

**Issue by frosas** [byohannes/job-listings-react#3]
The users may get confused if they don't see the cursor changing when they hover over a clickable element.

Notice how the design details this:

![ydrsnjsdiszx1vqopnwd](https://user-images.githubusercontent.com/50098/83953231-8a499580-a836-11ea-865c-43f463bd45b2.jpg)

**Comment by byohannes** [comment]
Thanks for this @frosas I have updated the code now and hover over clickable elements is available from now.

**Comment by frosas** [comment]
Cool. Did you publish the changes to Netlify?

**Comment by byohannes** [comment]
Yes, I have pushed the code but Netlify is failing to publish the codes and I am working on it

**Comment by byohannes** [comment]
it is published now  Francesc, and ready to view the netlify link

**Comment by frosas** [comment]
Looks better now 👍

Btw, do you know what would be the cherry on top? A `cursor: pointer`. But I'll leave this to your discretion.
